### ISSUE TITLE
What are the difference between in-domain and zero-shot cateogries?

### ISSUE THREAD

**Issue by zhimin-z** [rowanz/hellaswag#7]
I check the paper examples but still feel confused, is there a definition around?

**Comment by NishantWankhade** [comment]
@rowanz Can you please provide some formula for those accuracy calculations Or give some references ?

**Comment by zhimin-z** [comment]
Paper: https://aclanthology.org/P19-1472.pdf
![image](https://github.com/rowanz/hellaswag/assets/8592144/e8e7cdef-09a4-4966-9fb2-f14be0a24ac2)

**Comment by NishantWankhade** [comment]
Thank you for the paper.

**Comment by zhimin-z** [comment]
> Thank you for the paper.

What are the differences after all?

**Comment by NishantWankhade** [comment]
I believe : 
- In-domain ---> Context on which the dataset is trained 
- Zero shot ---> Context which is directly used for testing apart from the context present at the time of training
